### ISSUE TITLE
Can cellist itself use a proxy server to service requests ?

### ISSUE THREAD

**Issue by mdorion** [patr0nus/cellist-support#24]
Hello, my company uses a corporate proxy Squid through which all external http/https traffic must flow. This proxy is configured in OSX's Network preference so it works transparently with all other mac apps I use.

It seems Cellist is not recognizing that it has to itself use a proxy server and therefore fails to service http requests from its clients.

The only solution I've come across is to get off the corporate network and tether with my personal iPhone which is t a lot of hassle as I then must configure client devices under test (in my case Android and iOS mobile devices) to also use my personal iPhone as access point (so that test device can connect to Cellist on my mac).

Is there a way to have Cellist flow traffic through this other proxy ?

Thanks

**Comment by mdorion** [comment]
Apologies, I have just noticed the same question asked (and answered) in the "closed" forums items.

Thanks so much for a great tool and thanks for being active in the forums.

**Comment by mdorion** [comment]
Closed issue #13 provides solution for http (by overriding the http.request method via the console).
Is there an equivalent solution for https ?

**Comment by patr0nus** [comment]
HTTPS uses HTTP Tunnelling to get through the proxy, making the overriding much more tricking. I tried to figure out a solution but things got so complex that it was hardly possible to make it work.

The proxy support may be added as a feature to Cellist in the future. But sorry, no solution for HTTPS for now.

**Comment by mdorion** [comment]
Thank you for taking the time to respond. Hopefully https will be implemented in the future. Thank you for making Cellist!
